name: Run Backend Tests

on: 
  push:
    branches:
      - main  # 触发条件：推送到 main 分支
  pull_request:
    branches:
      - main  # 触发条件：有 PR 提交到 main 分支

jobs:
  test:
    runs-on: ubuntu-latest  # 在 Ubuntu 机器上运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 使用 Node.js 18.x 版本

      - name: Install dependencies
        run: |
          cd server
          npm install  # 安装后端依赖

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
          mongodb-port: 27017

      - name: Create .env file
        run: |
          cd server
          echo "MONGODB_URI=mongodb://localhost:27017/test_db" > .env
          echo "JWT_SECRET=test_secret_key" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "CALLBACK_URL=http://localhost:5002/auth/google/callback" >> .env

      - name: Run Tests
        run: |
          cd server
          npx mocha tests/**/*.js --timeout 10000  # 运行 server/tests 目录下的所有测试文件
