# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Frontend CI/CD

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm' # or 'yarn' if you're using Yarn

#       - name: Install dependencies
#         run: npm ci # or yarn install

#       - name: Run tests
#         run: npm test # or yarn test

#       - name: Build frontend
#         run: npm run build --if-present # or yarn build

#       # - name: Deploy (optional)
#       #   run: |
#       #     echo "Add deployment step here"